### ISSUE TITLE
Regression in 1.0.34

### ISSUE THREAD

**Issue by ABAG603** [keidarcy/e1s#224]
Hi,

there is regression related to the theming introduced in v1.0.34. I have BgColor set to #1e1e2e in my config but background is being reset to #282828. Before that version it was picked up correctly.
My full config is:
```
colors:
  BgColor: "#1e1e2e" 
  FgColor: "#cdd6f4"
  BorderColor: "#585b70"
  Black: "#45475a"
  Red: "#f38ba8"
  Green: "#a6e3a1"
  Yellow: "#f9e2af"
  Blue: "#89b4fa"
  Magenta: "#f5c2e7"
  Cyan: "#94e2d5"
  Gray: "#9399b2"
```
